services:
  - type: web
    name: batterytech-api
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: RATE_LIMIT
        value: 100
    autoDeploy: true
    healthCheckPath: /health